# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "This Week In Erlang"

author:
  twitter:          gootik
  github:           gootik
  medium:           gootik

copyright:
  year:             2017
  name:             gootik

# Google-analytics
google-analytics:
  id:               ""

# Disqus
disqus:
  id:               "this-week-in-erlang"

# URL
url:                "https://gootik.github.io/this-week-in-erlang"
# url:                "http://localhost:4000" # use this url when you develop
baseurl:            "/"


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Europe/London
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - name:           "Archive"
    url:            "/archive"
  - name:           "Tags"
    url:            "/tags"
  - name:           "Github"
    url:            "https://github.com/gootik/this-week-in-erlang"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-admin
  - jekyll-feed
  - jekyll-twitter-plugin

plugins: ['jekyll-twitter-plugin']

exclude:            [vendor]
